apiVersion: v1
kind: PersistentVolume
metadata:
  name: niiinja-data
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: niiinja-data
    fsType: ext4
